### ISSUE TITLE
you need set app_name in your config

### ISSUE THREAD

**Issue by kalashnikovisme** [zhangsoledad/alchemic_avatar#2]
I've added app_name to `config/config.exs`

``` elixir
config :alchemic_avatar,
  cache_base_path: "static",             # default is "static"
  colors_palette: :iwanthue,             # default is :google
  weight: 500,                           # default is 300
  annotate_position: "-0+10"             # default is -0+5
  app_name: :phoenix_first_app
```

I'm new in this stack. My app here
https://github.com/kalashnikovisme/phoenix_first_app

**Comment by zhangsoledad** [comment]
app_name is necessary,
if you use release tool like [distillery](https://github.com/bitwalker/distillery), it will break you project into component parts, the way to get priv path

``` erlang
:code.priv_dir(AlchemicAvatar.Config.app_name)
```

**Comment by kalashnikovisme** [comment]
I have problem with this lib.
I've added app_name to my config.exs and then I have error

`you need set app_name in your config`

**Comment by zhangsoledad** [comment]
@kalashnikovisme  seems you miss ','  in end of line 5
should be

``` elixir
annotate_position: "-0+10",            
app_name: :phoenix_first_app
```

Readme has the problem, i will fix this

**Comment by kalashnikovisme** [comment]
@zhangsoledad Yes. You're right. Thnx!!
